name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go stable
      uses: actions/setup-go@v4
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go mod download
      working-directory: oidc

    - name: Build
      run: make build
      working-directory: oidc

    - name: Test
      run: make test
      working-directory: oidc

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.1.2
        working-directory: oidc
