name: Package
on:
  push: {}
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y libpam0g-dev

      - name: Install nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.6.0

      - name: Build RPM
        run: make rpm
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm
          path: "pam_oidc-*.rpm"
      - name: Upload shared object file
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: pam_oidc.so
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            pam_oidc-*.rpm
